### ISSUE TITLE
allow symlink only option for `meta npm link`

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/meta-npm#2]
some users like to have separate physical checkouts for different branches of their meta repos. because of this, having global linkages for child projects can cause collisions. 

we want to have the ability to say `meta npm link --symlink` to do local symlinking only.

**Comment by vmx** [comment]
Looks like it is fixed with the `meta npm symlink` command introduced in https://github.com/mateodelnorte/meta-npm/pull/3.
